- project:
    name: tungstenfabric/tf-vro-plugin
    check:
      jobs:
        - contrail-build-vro-plugin
    gate:
      jobs:
        - contrail-build-vro-plugin

- job:
    name: contrail-build-vro-plugin
    description: |
      Job that builds tungstenfabric/tf-vro-plugin project.
    voting: True
    parent: contrail-vnc-base2
    required-projects:
      - tungstenfabric/tf-vro-plugin
    run: playbooks/contrail-build-vro-plugin/run.yaml
    nodeset:
      nodes:
        - name: builder
          label: centos-7-4-builder
